// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocalToken() {
  return window['go']['main']['App']['GetLocalToken']();
}

export function GetServerInfo() {
  return window['go']['main']['App']['GetServerInfo']();
}

export function GetStartupURL() {
  return window['go']['main']['App']['GetStartupURL']();
}

export function Handler() {
  return window['go']['main']['App']['Handler']();
}

export function PostponeUpdate(arg1) {
  return window['go']['main']['App']['PostponeUpdate'](arg1);
}

export function RegenerateLocalToken() {
  return window['go']['main']['App']['RegenerateLocalToken']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetStartupURL(arg1) {
  return window['go']['main']['App']['SetStartupURL'](arg1);
}
