// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {http} from '../models';

export function GetLocalToken():Promise<string>;

export function GetServerInfo():Promise<main.ServerInfo>;

export function GetStartupURL():Promise<string>;

export function Handler():Promise<http.Handler>;

export function PostponeUpdate(arg1:string):Promise<void>;

export function RegenerateLocalToken():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SetStartupURL(arg1:string):Promise<void>;
